### ISSUE TITLE
asdf can't find the executable

### ISSUE THREAD

**Issue by NigelThorne** [cometkim/asdf-grain#3]
I just installed 

> asdf plugin install grain

then 
> asdf install grain

and got 0.5.2

> asdg global grain 0.5.2

so install globally...

but when I

> asdf reshim 

I got no grain shim

When I checked 

> asdf which grain

No grain executable found for grain 0.5.2

so... 
I looked in the .asdf folder. 
I moved the grain executable  from `/home/nigel/.asdf/installs/grain/0.5.2/bin/grain/grain`
to `/home/nigel/.asdf/installs/grain/0.5.2/bin/grain`

then asdf could find it. 

> asdf which grain
> /home/nigel/.asdf/installs/grain/0.5.2/bin/grain

and then reshim could also find it. 
and now it's working. 
Oh .. I also had to `chmod +x grain` to make it executable. 

not sure what went wrong... but it's working now.

**Comment by s0kil** [comment]
To solve the issue, first move the grain executable from `~/.asdf/installs/grain/0.5.2/bin/grain/grain`
to `~/.asdf/installs/grain/0.5.2/bin/grain`, and then run `asdf reshim`.

**Comment by joprice** [comment]
Does the path here just need to remove the "/grain" suffix? https://github.com/cometkim/asdf-grain/blob/main/bin/install#L16
